# Site settings
title: Elon的橡树园
SEOTitle: Elon的博客 | 知秋一叶
header-img: img/accompany-desk.jpg
email: hangyang1212{at}gmail.com
description: "Even though I walk through the darkest valley, I will fear no evil, for you are with me."
keyword: "Elon, Elon's Blog, 知秋一叶的博客, 知秋一叶, iOS, Apple, iPhone"
url: "http://www.elonhangyang.com"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/elon-hangyang/elon-hangyang.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Your time is limited, so dont waste it living someone else's life. Have the courage to follow your heart and intuition."
sidebar-avatar: /img/avatar_m.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
zhihu_username:     elon-hangyang
github_username:    elon-hangyang
jianshu_username:   d710132d0869
#facebook_username:  elon-hangyang




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: elon-hangyang

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 54b52a4d47affae4f98f                            #生成的clientID
  clientSecret: 3c94dac8bd197f0b04a8ba57814d6c0fa946a6d4    #生成的clientSecret
  repo: elon-hangyang.github.io    #仓库名称
  owner: elon-hangyang    #github用户名
  admin: elon-hangyang
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-166797481-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "WY",
        href: "http://zhengwuyang.com"
    },{
        title: "MKyong",
        href: "https://mkyong.com/"
    },{
        title: "简书·HY",
        href: "http://www.jianshu.com/u/d710132d0869"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
